name: Notify Discord on new HTML file

on:
  push:
    paths:
      - 'Daily/*.html'

jobs:
  notify-discord:
    runs-on: ubuntu-latest

    steps:
      # 检查出代码，拉取完整的 Git 历史
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # 安装 Python
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'  # 可以指定你需要的 Python 版本

      # 运行 Python 脚本
      - name: Send notification to Discord
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          # 创建一个 Python 脚本并运行
          echo "import os
import requests

new_files = os.popen('git diff --diff-filter=A --name-only ${{ github.event.before }} ${{ github.sha }} | grep \".html\"').read().strip()

if new_files:
    message = f'**Papulatus Daily**\\nhttps://jancy-49.github.io/Papulatus-Daily/Daily/{new_files}'
    data = {'content': message}
    response = requests.post(os.getenv('DISCORD_WEBHOOK_URL'), json=data)
    print(response.text)
else:
    print('No new HTML files detected.')" > notify_discord.py

          python notify_discord.py
