name: Notify Discord on new HTML file

on:
  push:
    paths:
      - '**/*.html'

jobs:
  notify-discord:
    runs-on: ubuntu-latest

    steps:
      # 检查出代码，拉取完整的 Git 历史
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # 安装 Python
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'  # 可以指定你需要的 Python 版本
          
      # 安装 requests 库
      - name: Install requests
        run: |
          python -m pip install --upgrade pip  # 更新 pip
          pip install requests  # 安装 requests 库

      # 运行 Python 脚本
      - name: Send notification to Discord
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          # 创建一个 Python 脚本并运行
          echo "import os
          import re
          import requests
          new_files = os.popen('git diff --diff-filter=A --name-only ${{ github.event.before }} ${{ github.sha }} | grep \".html\"').read().strip()
          if 'Papulatus_Daily' in new_files:
            Date = re.match(r'Daily/Papulatus_Daily\((\d+-\d+-\d+)\).html', new_files).group(1)
            embed = {"embeds": [{"title": f"Papulatus Daily ({Date})",
                                 "description": f"Papulatus Daily ({Date})",
                                 "color": 0x00ff00,
                                 "image": {"url": f"https://jancy-1256059393.cos.ap-guangzhou.myqcloud.com/Daily/image/{Date}.png"}}]}
            response = requests.post(os.getenv('DISCORD_WEBHOOK_URL'), data=json.dumps(embed))
            print(response.text)
          else:
            print('No new HTML files detected.')" > notify_discord.py

          python notify_discord.py
